No MK, No heroes
Valokoodari/btd6-ahk pull request #93
Opened 2023-04-13 12:29 UTC by kobisjeruk

First time using github, hopefully I'm doing it right. This is the main.ahk edited to remove hero check, trim down the time and change the hotkey for start (Z) and stop/reload (X).

2023-04-14 13:24 UTC, Valokoodari commented
I have not yet tested this properly but just by skimming through the changes this seems really good for the most part.

However, I did notice some code formatting problems (mostly mixed tabs and spaces, and trailing whitespace) which will need to be fixed before merging. Also the changes made in a63a1b0 will not be merged aside from the removal of the hero check as the hotkeys should not be anything common like cut and undo and the sleep times have been chosen to not spam the log too much. Even the hero check removal should be done properly instead of just commenting out the function call.

I will likely have time tomorrow or the day after that so I'll fix all these problems then. Also please name your commits properly in the future if you make any more changes as "Add files via upload" doesn't describe the changes made at all.

2023-04-15 12:02 UTC, Valokoodari commented on README.md
> +- Sniper Monkey 302
This should be at least 322

2023-04-15 12:08 UTC, Valokoodari requested changes
Every map has now been tested successfully at least once so this is almost done. Just some small fixes required.

2023-04-15 12:08 UTC, Valokoodari commented on maps/bloody_puddles.ahk
> +    Upgrade(1180,190,2,0,0)     ; Sub: 000 -> 200
There's something wrong here

2023-04-15 12:42 UTC, Valokoodari approved these changes
Just going to test this for a few more hours but otherwise everything should be fine now.

2023-04-16 07:33 UTC, Valokoodari commented
Result so far are 175 victories and 14 defeats which isn't quite as good as the older strategies (~1000 victories to 10 defeats). I still think the results are good enough so I'm merging this now.

2023-04-16 07:34 UTC, merged

2023-04-17 06:59 UTC, kobisjeruk commented
Honestly, more than anything else I am quite shocked to see that 14 defeats. Were any particular map prove to be problematic? I wish I could reproduce the result but I am facing a different problem (not really a problem but sometimes script got randomly stuck at the victory screen).

2023-04-17 08:39 UTC, Valokoodari commented
Currently at 414 victories and 28 defeats. All of the defeats have been on either Ravine (9) or Workshop (19). On Workshop the problem is clear: sometimes too many bloons leak and the script cannot afford the spike factory. On Ravine I haven't yet seen what the problem is but I suspect it to be something similar.

2023-04-17 15:17 UTC, kobisjeruk commented
I suspected it is something related to timing. Almost always I tried to have some leeway before purchase/upgrade. Mostly if the purchase or upgrade use up almost all cash (like say <$50 left), I'd wait until the next round instead. Ravine is one where it is quite 'tight'. I didnt realize it happened in Workshop. A simple solution is to bump the purchase/upgrade to the next round. I guess you fix it already?

2023-04-17 15:27 UTC, Valokoodari commented
Yeah, I fixed them already in commits 1db789cac5d1cfb5541cf5d36adaa378349a9388 and a3c755959adc728b818fc84b839eae12d264d116.